version: '3.8'

services:
    mymongodb:
        image: mongo
        restart: unless-stopped
        ports:
            - '27018:27017'
        volumes:
            - ./mongo-db:/data/db
        networks:
            - my-network
    s3:
        image: minio/minio
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        ports:
            - '9000:9000'
            - '9099:9099'
        volumes:
            - ./storage-minio:/data
        command: server --address ":9099" --console-address ":9000" /data
        networks:
            - my-network
        
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        image: frontend
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - ./FrontEnd:/usr/src/app
        depends_on:
            - server
        networks:
            - my-network


    admin:
        build:
            dockerfile: Dockerfile
            context: ./admin
        image: admin
        restart: unless-stopped
        ports:
            - '3001:3001'
        depends_on:
            - server
        networks:
            - my-network    

    server:
        build:
            dockerfile: Dockerfile
            context: ./backend
        image: server
        env_file: docker-compose.env
        restart: unless-stopped
        ports:
            - '5000:5000'
        depends_on:
            - mymongodb
            - s3
        networks:
            - my-network

networks:
    my-network:
        driver: bridge

volumes:
    mongo-db:
        driver: local
    storage-minio:
        driver: local
